# Generated by Django 5.0.3 on 2024-03-26 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('callsign', models.CharField(max_length=20)),
                ('founded_year', models.IntegerField()),
                ('base_airport', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_serial_number', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('number_of_engines', models.IntegerField()),
                ('operator_airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlines.airline')),
            ],
        ),
    ]
